package io.github.gyai.projects.ability.editor;

import io.github.gyai.projects.ability.*;
import io.github.gyai.projects.combat.damage.*;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.util.*;

/** Fixed endian v1 wire format. Every string is UTF-8 length-prefixed u16; no trailing bytes accepted. */
public final class SkillVfxEditorProtocol {
    public static final int VERSION=1, MAX_PACKET=64*1024, MAX_ABILITIES=64, MAX_ACTIONS=64, MAX_HOOKS=5, MAX_EMISSIONS=16, MAX_PRIMITIVES=16, MAX_POINTS=8, MAX_STRING=256;
    public enum Operation { CATALOG, FETCH, APPLY_VISUAL_SESSION, REVERT_VISUAL_SESSION }
    public enum Status { OK, PERMISSION_DENIED, MALFORMED, STALE, NOT_FOUND, CONFLICT }
    public record Request(Operation operation,long correlation,UUID session,String abilityId,long revision,String baseFingerprint,String effectiveFingerprint,AbilityVisualDefinition visual) { }
    public record State(Status status,long correlation,UUID session,List<SkillVfxEditorService.CatalogItem> catalog,SkillVfxEditorService.Snapshot snapshot,boolean previewAllowed,String message) { }
    private SkillVfxEditorProtocol() { }
    public static byte[] encodeRequest(Request v) { validateRequest(v); return out(o->{o.writeByte(VERSION);o.writeByte(v.operation().ordinal());o.writeLong(v.correlation());uuid(o,v.session());str(o,v.abilityId());o.writeLong(v.revision());str(o,v.baseFingerprint());str(o,v.effectiveFingerprint());o.writeBoolean(v.visual()!=null);if(v.visual()!=null)visual(o,v.visual());}); }
    public static Request decodeRequest(byte[] b) { return in(b,i->{version(i); Operation op=enumValue(Operation.values(),i.readUnsignedByte()); long c=i.readLong();UUID s=uuid(i);String id=str(i);long r=i.readLong();String base=str(i),effective=str(i);AbilityVisualDefinition v=i.readBoolean()?visual(i):null;Request result=new Request(op,c,s,id,r,base,effective,v);validateRequest(result);return result;}); }
    public static byte[] encodeState(State v) { if(v==null||v.status()==null||v.correlation()<=0||v.session()==null||v.catalog()==null||v.catalog().size()>MAX_ABILITIES)throw new IllegalArgumentException("state"); return out(o->{o.writeByte(VERSION);o.writeByte(v.status().ordinal());o.writeLong(v.correlation());uuid(o,v.session());o.writeBoolean(v.previewAllowed());str(o,v.message());o.writeShort(v.catalog().size());validateCatalog(v.catalog());for(var x:v.catalog()){str(o,x.abilityId());str(o,x.displayName());o.writeBoolean(x.hasVisual());str(o,x.visualId());o.writeLong(x.revision());str(o,x.baseFingerprint());str(o,x.effectiveFingerprint());o.writeBoolean(x.sessionOverride());}o.writeBoolean(v.snapshot()!=null);if(v.snapshot()!=null)snapshot(o,v.snapshot());}); }
    public static State decodeState(byte[] b) { return in(b,i->{version(i);Status s=enumValue(Status.values(),i.readUnsignedByte());long c=i.readLong();if(c<=0)throw new IOException("correlation");UUID session=uuid(i);boolean preview=i.readBoolean();String message=str(i);int n=i.readUnsignedShort();if(n>MAX_ABILITIES)throw new IOException("catalog");List<SkillVfxEditorService.CatalogItem> catalog=new ArrayList<>();for(int x=0;x<n;x++){String ability=str(i),name=str(i);boolean has=i.readBoolean();catalog.add(new SkillVfxEditorService.CatalogItem(ability,name,str(i),has,i.readLong(),str(i),str(i),i.readBoolean()));}validateCatalog(catalog);SkillVfxEditorService.Snapshot snapshot=i.readBoolean()?snapshot(i):null;return new State(s,c,session,List.copyOf(catalog),snapshot,preview,message);}); }
    public static byte[] encodeVisual(AbilityVisualDefinition visual) { return out(o->visual(o,visual)); }
    private static void snapshot(DataOutputStream o,SkillVfxEditorService.Snapshot s)throws IOException { ability(o,s.ability());str(o,s.visualId());visual(o,s.base());visual(o,s.effective());o.writeLong(s.revision());str(o,s.baseFingerprint());str(o,s.effectiveFingerprint());o.writeBoolean(s.sessionOverride()); }
    private static SkillVfxEditorService.Snapshot snapshot(DataInputStream i)throws IOException { AbilityDefinition a=ability(i);String id=str(i);AbilityVisualDefinition base=visual(i),effective=visual(i);return new SkillVfxEditorService.Snapshot(a,id,base,effective,i.readLong(),str(i),str(i),i.readBoolean()); }
    private static void ability(DataOutputStream o,AbilityDefinition a)throws IOException {if(a==null||a.steps().size()<1||a.steps().size()>MAX_ACTIONS)throw new IOException("actions");o.writeByte(a.schemaVersion());str(o,a.id());str(o,a.displayName());o.writeByte(a.steps().size());for(var x:a.steps()){if(x instanceof AbilityDefinition.Wait w){o.writeByte(0);o.writeInt(w.ticks());}else if(x instanceof AbilityDefinition.CircleTelegraph c){o.writeByte(1);o.writeByte(c.target().ordinal());o.writeByte(c.origin().ordinal());o.writeDouble(c.radius());o.writeInt(c.durationTicks());o.writeBoolean(c.lockAtCreation());}else if(x instanceof AbilityDefinition.Damage d){o.writeByte(2);o.writeByte(d.target().ordinal());o.writeByte(d.damageType().ordinal());o.writeByte(d.damageKind().ordinal());o.writeDouble(d.fixedDamage());o.writeDouble(d.coefficient());o.writeBoolean(d.criticalAllowed());metadata(o,d.metadata());}else throw new IOException("action");}}
    private static AbilityDefinition ability(DataInputStream i)throws IOException {int ver=i.readUnsignedByte();String id=str(i),name=str(i);int n=i.readUnsignedByte();if(n==0||n>MAX_ACTIONS)throw new IOException("actions");List<AbilityDefinition.ActionSpec> steps=new ArrayList<>();for(int x=0;x<n;x++){switch(i.readUnsignedByte()){case 0->steps.add(new AbilityDefinition.Wait(i.readInt()));case 1->steps.add(new AbilityDefinition.CircleTelegraph(enumValue(TargetSelector.values(),i.readUnsignedByte()),enumValue(TargetSelector.values(),i.readUnsignedByte()),i.readDouble(),i.readInt(),i.readBoolean()));case 2->steps.add(new AbilityDefinition.Damage(enumValue(TargetSelector.values(),i.readUnsignedByte()),enumValue(DamageType.values(),i.readUnsignedByte()),enumValue(DamageKind.values(),i.readUnsignedByte()),i.readDouble(),i.readDouble(),i.readBoolean(),metadata(i)));default->throw new IOException("action");}}return new AbilityDefinition(ver,id,name,steps);}
    private static void metadata(DataOutputStream o,AttackMetadata m)throws IOException {o.writeShort(m.tags().stream().mapToInt(Enum::ordinal).reduce(0,(a,b)->a|(1<<b)));for(DamageElement e:DamageElement.values()){o.writeDouble(m.elements().value(e));o.writeDouble(m.elements().scalingRate(e));}}
    private static AttackMetadata metadata(DataInputStream i)throws IOException {int mask=i.readUnsignedShort();EnumSet<AttackTag> tags=EnumSet.noneOf(AttackTag.class);for(AttackTag t:AttackTag.values())if((mask&(1<<t.ordinal()))!=0)tags.add(t);EnumMap<DamageElement,Double> values=new EnumMap<>(DamageElement.class),rates=new EnumMap<>(DamageElement.class);for(DamageElement e:DamageElement.values()){double v=i.readDouble(),r=i.readDouble();if(v!=0)values.put(e,v);if(r!=0)rates.put(e,r);}return new AttackMetadata(tags,new ElementProfile(values,rates));}
    private static void visual(DataOutputStream o,AbilityVisualDefinition v)throws IOException {if(v==null||v.bindings().size()>MAX_HOOKS)throw new IOException("hooks");o.writeByte(v.schemaVersion());str(o,v.id());o.writeByte(v.bindings().size());for(var h:v.bindings()){if(h.emissions().isEmpty()||h.emissions().size()>MAX_EMISSIONS)throw new IOException("emissions");o.writeByte(h.hook().ordinal());o.writeByte(h.emissions().size());for(var e:h.emissions()){if(e.primitives().isEmpty()||e.primitives().size()>MAX_PRIMITIVES)throw new IOException("primitives");str(o,e.id());o.writeInt(e.actionIndex());o.writeByte(e.primitives().size());for(var p:e.primitives())primitive(o,p);}}}
    private static AbilityVisualDefinition visual(DataInputStream i)throws IOException {int ver=i.readUnsignedByte();String id=str(i);int hc=i.readUnsignedByte();if(hc>MAX_HOOKS)throw new IOException("hooks");List<AbilityVisualDefinition.HookBinding> hs=new ArrayList<>();for(int h=0;h<hc;h++){var hook=enumValue(AbilityLifecycleEvent.Hook.values(),i.readUnsignedByte());int ec=i.readUnsignedByte();if(ec==0||ec>MAX_EMISSIONS)throw new IOException("emissions");List<AbilityVisualDefinition.Emission> es=new ArrayList<>();for(int e=0;e<ec;e++){String eid=str(i);int ai=i.readInt();int pc=i.readUnsignedByte();if(pc==0||pc>MAX_PRIMITIVES)throw new IOException("primitives");List<AbilityVisualDefinition.PrimitiveSpec> ps=new ArrayList<>();for(int p=0;p<pc;p++)ps.add(primitive(i));es.add(new AbilityVisualDefinition.Emission(eid,ai,ps));}hs.add(new AbilityVisualDefinition.HookBinding(hook,es));}return new AbilityVisualDefinition(ver,id,hs);}
    private static void primitive(DataOutputStream o,AbilityVisualDefinition.PrimitiveSpec p)throws IOException {if(p==null||p.controlPoints().size()>MAX_POINTS)throw new IOException("points");str(o,p.id());o.writeByte(p.type().ordinal());o.writeInt(p.delayTicks());o.writeInt(p.durationTicks());o.writeInt(p.argb());o.writeDouble(p.width());o.writeInt(p.density());o.writeLong(p.seed());vec(o,p.localOffset());o.writeDouble(p.yawRadians());scalar(o,p.size());scalar(o,p.radius());scalar(o,p.length());scalar(o,p.height());scalar(o,p.angle());scalar(o,p.startAngle());scalar(o,p.sweepAngle());scalar(o,p.turns());o.writeInt(p.count());o.writeByte(p.controlPoints().size());for(var x:p.controlPoints())vec(o,x);}
    private static AbilityVisualDefinition.PrimitiveSpec primitive(DataInputStream i)throws IOException {String id=str(i);var t=enumValue(AbilityVisualDefinition.PrimitiveType.values(),i.readUnsignedByte());int d=i.readInt(),du=i.readInt(),argb=i.readInt();double width=i.readDouble();int den=i.readInt();long seed=i.readLong();var off=vec(i);double yaw=i.readDouble();var size=scalar(i);var radius=scalar(i);var length=scalar(i);var height=scalar(i);var angle=scalar(i);var start=scalar(i);var sweep=scalar(i);var turns=scalar(i);int count=i.readInt(),n=i.readUnsignedByte();if(n>MAX_POINTS)throw new IOException("points");List<AbilityVisualDefinition.Vec> cp=new ArrayList<>();for(int x=0;x<n;x++)cp.add(vec(i));return new AbilityVisualDefinition.PrimitiveSpec(id,t,d,du,argb,width,den,seed,off,yaw,size,radius,length,height,angle,start,sweep,turns,count,cp);}
    private static void scalar(DataOutputStream o,AbilityVisualDefinition.Scalar s)throws IOException {if(s==null)o.writeByte(0);else if(s instanceof AbilityVisualDefinition.Literal l){o.writeByte(1);o.writeDouble(l.value());}else{o.writeByte(2);o.writeByte(((AbilityVisualDefinition.ActionField)s).ordinal());}}
    private static AbilityVisualDefinition.Scalar scalar(DataInputStream i)throws IOException {return switch(i.readUnsignedByte()){case 0->null;case 1->new AbilityVisualDefinition.Literal(i.readDouble());case 2->enumValue(AbilityVisualDefinition.ActionField.values(),i.readUnsignedByte());default->throw new IOException("scalar");};}
    private static void vec(DataOutputStream o,AbilityVisualDefinition.Vec v)throws IOException{o.writeDouble(v.x());o.writeDouble(v.y());o.writeDouble(v.z());} private static AbilityVisualDefinition.Vec vec(DataInputStream i)throws IOException{return new AbilityVisualDefinition.Vec(i.readDouble(),i.readDouble(),i.readDouble());}
    private static void uuid(DataOutputStream o,UUID v)throws IOException{if(v==null)throw new IOException("uuid");o.writeLong(v.getMostSignificantBits());o.writeLong(v.getLeastSignificantBits());}private static UUID uuid(DataInputStream i)throws IOException{return new UUID(i.readLong(),i.readLong());}
    private static void validateCatalog(List<SkillVfxEditorService.CatalogItem> catalog)throws IOException {String previous="";for(var x:catalog){if(x==null||x.abilityId()==null||x.displayName()==null||x.visualId()==null||x.baseFingerprint()==null||x.effectiveFingerprint()==null||x.abilityId().compareTo(previous)<=0)throw new IOException("catalog");if(!x.hasVisual()&&(!x.visualId().isEmpty()||!x.baseFingerprint().isEmpty()||!x.effectiveFingerprint().isEmpty()||x.sessionOverride()))throw new IOException("unbound");if(x.hasVisual()&&(x.visualId().isBlank()||x.baseFingerprint().isBlank()||x.effectiveFingerprint().isBlank()))throw new IOException("bound");previous=x.abilityId();}}
    private static void str(DataOutputStream o,String s)throws IOException{if(s==null)throw new IOException("string");byte[] b=s.getBytes(StandardCharsets.UTF_8);if(b.length>MAX_STRING)throw new IOException("string");o.writeShort(b.length);o.write(b);}private static String str(DataInputStream i)throws IOException{int n=i.readUnsignedShort();if(n>MAX_STRING)throw new IOException("string");byte[] b=i.readNBytes(n);if(b.length!=n)throw new EOFException();String s=new String(b,StandardCharsets.UTF_8);if(!Arrays.equals(b,s.getBytes(StandardCharsets.UTF_8)))throw new IOException("utf8");return s;}
    private static <T> T enumValue(T[] values,int ordinal)throws IOException{if(ordinal<0||ordinal>=values.length)throw new IOException("enum");return values[ordinal];}private static void version(DataInputStream i)throws IOException{if(i.readUnsignedByte()!=VERSION)throw new IOException("version");}
    private static void validateRequest(Request r) { if(r==null||r.operation()==null||r.correlation()<=0||r.session()==null||r.abilityId()==null||r.baseFingerprint()==null||r.effectiveFingerprint()==null)throw new IllegalArgumentException("request");switch(r.operation()){case CATALOG->{if(!r.abilityId().isEmpty()||r.revision()!=0||!r.baseFingerprint().isEmpty()||!r.effectiveFingerprint().isEmpty()||r.visual()!=null)throw new IllegalArgumentException("catalog shape");}case FETCH->{if(r.abilityId().isBlank()||r.revision()!=0||!r.baseFingerprint().isEmpty()||!r.effectiveFingerprint().isEmpty()||r.visual()!=null)throw new IllegalArgumentException("fetch shape");}case APPLY_VISUAL_SESSION->{if(r.abilityId().isBlank()||r.revision()<0||r.baseFingerprint().isBlank()||r.effectiveFingerprint().isBlank()||r.visual()==null)throw new IllegalArgumentException("apply shape");}case REVERT_VISUAL_SESSION->{if(r.abilityId().isBlank()||r.revision()<0||r.baseFingerprint().isBlank()||r.effectiveFingerprint().isBlank()||r.visual()!=null)throw new IllegalArgumentException("revert shape");}}}
    private interface Writer {void write(DataOutputStream o)throws IOException;} private interface Reader<T>{T read(DataInputStream i)throws IOException;}private static byte[] out(Writer w){try{ByteArrayOutputStream b=new ByteArrayOutputStream();try(DataOutputStream o=new DataOutputStream(b)){w.write(o);}if(b.size()>MAX_PACKET)throw new IllegalArgumentException("packet");return b.toByteArray();}catch(IOException e){throw new IllegalArgumentException(e);}}private static <T>T in(byte[] b,Reader<T> r){if(b==null||b.length>MAX_PACKET)throw new IllegalArgumentException("packet");try(DataInputStream i=new DataInputStream(new ByteArrayInputStream(b))){T v=r.read(i);if(i.available()!=0)throw new IOException("trailing");return v;}catch(IOException|RuntimeException e){throw new IllegalArgumentException("Malformed skill editor packet",e);}}
}
