package io.github.gyai.projects.ability;

import io.github.gyai.projects.network.AbilityVfxPacket;
import java.nio.file.*; import java.util.*; import java.security.MessageDigest;

/** Executable pure contract coverage for visual definitions, hook exactness and wire bytes. */
public final class AbilityVisualFoundationTest {
 public static void main(String[] args)throws Exception { if(args.length>0){System.out.println(hex("particle".equals(args[0])?particleWire():AbilityVfxPacket.encode(canonical())));return;} definitionAndResolution(); primitiveMappings(); validationVectors(); lifecycleExactness(); adapterIsolationAndScalarResolution(); wireGolden(); appearanceRuntime(); System.out.println("Ability visual v0.1 foundation tests passed"); }
 static void definitionAndResolution(){
  AbilityVisualRegistry r=new AbilityVisualRegistry(); DevAbilityVisuals.registerInto(r); assert r.resolve(DevAbilityDefinitions.SHARED_ARCANE_BURST_ID).orElseThrow().id().equals(DevAbilityVisuals.ARCANE_BURST_VISUAL_ID); assert r.resolve("projects:missing").isEmpty(); r.bind(new AbilityVisualBinding("projects:stale","projects:vfx/stale")); assert r.resolve("projects:stale").isEmpty(); expect(()->r.register(DevAbilityVisuals.arcaneBurst())); expect(()->r.bind(new AbilityVisualBinding(DevAbilityDefinitions.SHARED_ARCANE_BURST_ID,"projects:vfx/other")));
  var p=new AbilityVisualDefinition.PrimitiveSpec("x",AbilityVisualDefinition.PrimitiveType.CIRCLE,0,1,0xff,1,1,1,new AbilityVisualDefinition.Vec(0,0,0),0,null,AbilityVisualDefinition.ActionField.RADIUS,null,null,null,null,null,null,0,List.of());
  expect(()->new AbilityVisualDefinition(2,"projects:x",List.of())); expect(()->new AbilityVisualDefinition(1,"projects:x",List.of(new AbilityVisualDefinition.HookBinding(AbilityLifecycleEvent.Hook.CAST,List.of(new AbilityVisualDefinition.Emission("a",-1,List.of(p)))),new AbilityVisualDefinition.HookBinding(AbilityLifecycleEvent.Hook.CAST,List.of(new AbilityVisualDefinition.Emission("b",-1,List.of(p)))))));
  expect(()->new AbilityVisualDefinition.Literal(Double.NaN)); expect(()->new AbilityVisualDefinition.PrimitiveSpec("x",AbilityVisualDefinition.PrimitiveType.CIRCLE,0,1200,0,1,1,1,new AbilityVisualDefinition.Vec(0,0,0),0,null,new AbilityVisualDefinition.Literal(1),null,null,null,null,null,null,65,List.of()));
  expect(()->new AbilityVisualDefinition.PrimitiveSpec("size-over",AbilityVisualDefinition.PrimitiveType.POINT,0,1,0,1,1,1,new AbilityVisualDefinition.Vec(0,0,0),0,new AbilityVisualDefinition.Literal(128.001),null,null,null,null,null,null,null,0,List.of())); expect(()->new AbilityVisualDefinition.PrimitiveSpec("radius-over",AbilityVisualDefinition.PrimitiveType.CIRCLE,0,1,0,1,1,1,new AbilityVisualDefinition.Vec(0,0,0),0,null,new AbilityVisualDefinition.Literal(128.001),null,null,null,null,null,null,0,List.of()));
 }
 static void primitiveMappings(){
  var z=List.<AbilityVisualDefinition.Vec>of(); var cp=List.of(new AbilityVisualDefinition.Vec(0,0,0),new AbilityVisualDefinition.Vec(1,0,0),new AbilityVisualDefinition.Vec(2,0,0));
  primitive(AbilityVisualDefinition.PrimitiveType.POINT,1,0,0,0,0,0,0,0,0,z); primitive(AbilityVisualDefinition.PrimitiveType.LINE,0,0,1,0,0,0,0,0,0,z); primitive(AbilityVisualDefinition.PrimitiveType.LINE,0,0,1,0,0,0,0,0,0,List.of(new AbilityVisualDefinition.Vec(0,0,0),new AbilityVisualDefinition.Vec(1,0,0))); primitive(AbilityVisualDefinition.PrimitiveType.ARC,0,1,0,0,0,0,1,0,0,z); primitive(AbilityVisualDefinition.PrimitiveType.CIRCLE,0,1,0,0,0,.5,0,0,0,z); primitive(AbilityVisualDefinition.PrimitiveType.CONE,0,0,1,0,1,0,0,0,0,z); primitive(AbilityVisualDefinition.PrimitiveType.SPIRAL,0,1,0,0,0,0,0,1,0,z); primitive(AbilityVisualDefinition.PrimitiveType.SPHERE,0,1,0,0,0,0,0,0,0,z); primitive(AbilityVisualDefinition.PrimitiveType.WAVE,0,1,1,1,0,0,0,0,0,z); primitive(AbilityVisualDefinition.PrimitiveType.BEZIER,0,0,0,0,0,0,0,0,0,cp); primitive(AbilityVisualDefinition.PrimitiveType.BURST,0,1,0,0,0,0,0,0,2,z);
  expect(()->primitive(AbilityVisualDefinition.PrimitiveType.CIRCLE,1,1,0,0,0,0,0,0,0,z)); expect(()->primitive(AbilityVisualDefinition.PrimitiveType.BURST,0,1,0,0,0,0,0,0,0,z)); expect(()->primitive(AbilityVisualDefinition.PrimitiveType.BEZIER,0,0,0,0,0,0,0,0,0,List.of()));
  primitive(AbilityVisualDefinition.PrimitiveType.POINT,128,0,0,0,0,0,0,0,0,z); primitive(AbilityVisualDefinition.PrimitiveType.CIRCLE,0,128,0,0,0,0,0,0,0,z); primitive(AbilityVisualDefinition.PrimitiveType.WAVE,0,1,128,128,0,0,0,0,0,z); primitive(AbilityVisualDefinition.PrimitiveType.ARC,0,1,0,0,0,0,4*Math.PI,0,0,z); primitive(AbilityVisualDefinition.PrimitiveType.SPIRAL,0,1,0,128,0,0,0,32,0,z);
  expect(()->primitive(AbilityVisualDefinition.PrimitiveType.POINT,128.0001,0,0,0,0,0,0,0,0,z)); expect(()->primitive(AbilityVisualDefinition.PrimitiveType.CIRCLE,0,128.0001,0,0,0,0,0,0,0,z)); expect(()->primitive(AbilityVisualDefinition.PrimitiveType.WAVE,0,1,128.0001,0,0,0,0,0,0,z)); expect(()->primitive(AbilityVisualDefinition.PrimitiveType.WAVE,0,1,1,128.0001,0,0,0,0,0,z)); expect(()->primitive(AbilityVisualDefinition.PrimitiveType.ARC,0,1,0,0,0,0,4*Math.PI+.001,0,0,z)); expect(()->primitive(AbilityVisualDefinition.PrimitiveType.SPIRAL,0,1,0,0,0,0,0,32.001,0,z)); expect(()->primitive(AbilityVisualDefinition.PrimitiveType.CONE,0,0,1,0,Math.PI,0,0,0,0,z));
 }
 static AbilityVfxPacket.Primitive primitive(AbilityVisualDefinition.PrimitiveType t,double s,double r,double l,double h,double a,double start,double sweep,double turns,int count,List<AbilityVisualDefinition.Vec> cp){return new AbilityVfxPacket.Primitive(t,0,1,0xff000000,1,1,1,new AbilityVisualDefinition.Vec(0,0,0),0,s,r,l,h,a,start,sweep,turns,count,cp);}
 static void validationVectors() throws Exception {
  Set<String> expected=Set.of("CONE_ANGLE_NEXT_DOWN_PI","CONE_ANGLE_PI","CONE_ANGLE_NEXT_UP_PI","CONE_ANGLE_POSITIVE_ZERO","CONE_ANGLE_NEGATIVE_ZERO","CONE_ANGLE_NEGATIVE","CIRCLE_SIZE_POSITIVE_ZERO","CIRCLE_SIZE_NEGATIVE_ZERO","CIRCLE_RADIUS_POSITIVE_ZERO","CIRCLE_RADIUS_NEGATIVE_ZERO","CIRCLE_RADIUS_ORDINARY"); Set<String> actual=new HashSet<>(); for(String line:Files.readAllLines(Path.of("src/test/resources/protocol/ability-vfx-validation-v1.txt"))){if(!line.isBlank()&&!line.startsWith("#")){String[] columns=line.split("\\|",-1);assert columns.length==5&&(columns[4].equals("ACCEPT")||columns[4].equals("REJECT"));actual.add(columns[0]);}} assert actual.equals(expected);
  var z=List.<AbilityVisualDefinition.Vec>of(); primitive(AbilityVisualDefinition.PrimitiveType.CONE,0,0,1,0,Math.nextDown(Math.PI),0,0,0,0,z); for(double angle:new double[]{Math.PI,Math.nextUp(Math.PI),0.0,-0.0,-1.0})expect(()->primitive(AbilityVisualDefinition.PrimitiveType.CONE,0,0,1,0,angle,0,0,0,0,z));
  primitive(AbilityVisualDefinition.PrimitiveType.CIRCLE,0,4,0,0,0,0,0,0,0,z); for(double size:new double[]{0.0,-0.0})primitive(AbilityVisualDefinition.PrimitiveType.CIRCLE,size,4,0,0,0,0,0,0,0,z); for(double radius:new double[]{0.0,-0.0})expect(()->primitive(AbilityVisualDefinition.PrimitiveType.CIRCLE,0,radius,0,0,0,0,0,0,0,z));
 }
 static void lifecycleExactness(){
  List<AbilityLifecycleEvent.Hook> hooks=new ArrayList<>(); AbilityCastContext.EntityRef s=new AbilityCastContext.EntityRef(UUID.randomUUID()),t=new AbilityCastContext.EntityRef(UUID.randomUUID()); AbilityCastContext c=new AbilityCastContext(UUID.randomUUID(),"projects:x",s,SourceKind.PLAYER,new AbilityCastContext.Origin(UUID.randomUUID(),"minecraft:overworld",0,0,0),t,Map.of());
  AbilityRuntime rt=new AbilityRuntime(AbilityRuntime.standardActions(),new Immediate(),x->true,(a,b,d,e)->new AbilityRuntime.TelegraphHandle(){public void detonate(){}public void cancel(){}public AnchorFrame anchor(){return frame(a);}},(a,b,d)->new AbilityRuntime.DamageOutcome(true,0,1,frame(a)),e->{hooks.add(e.hook());throw new IllegalStateException();},(a,b)->frame(a));
  rt.cast(new AbilityDefinition(1,"projects:x","x",List.of(new AbilityDefinition.CircleTelegraph(TargetSelector.PRIMARY_TARGET,TargetSelector.PRIMARY_TARGET,3,1,true),new AbilityDefinition.Damage(TargetSelector.PRIMARY_TARGET,io.github.gyai.projects.combat.damage.DamageType.MAGICAL,io.github.gyai.projects.combat.damage.DamageKind.DIRECT_SKILL,1,0,true,null))),c); assert hooks.equals(List.of(AbilityLifecycleEvent.Hook.CAST,AbilityLifecycleEvent.Hook.TELEGRAPH,AbilityLifecycleEvent.Hook.HIT,AbilityLifecycleEvent.Hook.EXPIRE));
 List<AbilityLifecycleEvent.Hook> zero=new ArrayList<>(); AbilityRuntime noHit=new AbilityRuntime(AbilityRuntime.standardActions(),new Immediate(),x->true,(a,b,d,e)->new AbilityRuntime.TelegraphHandle(){public void detonate(){}public void cancel(){}public AnchorFrame anchor(){return frame(a);}},(a,b,d)->new AbilityRuntime.DamageOutcome(false,0,0,frame(a)),e->zero.add(e.hook()),(a,b)->frame(a)); noHit.cast(new AbilityDefinition(1,"projects:y","y",List.of(new AbilityDefinition.Damage(TargetSelector.PRIMARY_TARGET,io.github.gyai.projects.combat.damage.DamageType.MAGICAL,io.github.gyai.projects.combat.damage.DamageKind.DIRECT_SKILL,1,0,true,null))),new AbilityCastContext(UUID.randomUUID(),"projects:y",s,SourceKind.PLAYER,c.origin(),t,Map.of())); assert !zero.contains(AbilityLifecycleEvent.Hook.HIT)&&zero.contains(AbilityLifecycleEvent.Hook.EXPIRE);
  List<AbilityLifecycleEvent.Hook> failed=new ArrayList<>(); AbilityRuntime fail=new AbilityRuntime(AbilityRuntime.standardActions(),(ticks,task)->()->{},x->true,(a,b,d,e)->new AbilityRuntime.TelegraphHandle(){public void detonate(){}public void cancel(){}public AnchorFrame anchor(){throw new IllegalStateException();}},(a,b,d)->new AbilityRuntime.DamageOutcome(true,0,1,frame(a)),e->failed.add(e.hook()),(a,b)->frame(a)); AbilityRuntime.Cast cast=fail.cast(new AbilityDefinition(1,"projects:z","z",List.of(new AbilityDefinition.Wait(1))),new AbilityCastContext(UUID.randomUUID(),"projects:z",s,SourceKind.PLAYER,c.origin(),t,Map.of())); cast.fail(); assert failed.equals(List.of(AbilityLifecycleEvent.Hook.CAST,AbilityLifecycleEvent.Hook.CANCEL));
  List<AbilityLifecycleEvent> cancelled=new ArrayList<>(); AbilityRuntime explicit=new AbilityRuntime(AbilityRuntime.standardActions(),(ticks,task)->()->{},x->true,(a,b,d,e)->new AbilityRuntime.TelegraphHandle(){public void detonate(){}public void cancel(){}public AnchorFrame anchor(){return frame(a);}},(a,b,d)->new AbilityRuntime.DamageOutcome(true,0,1,frame(a)),cancelled::add,(a,b)->frame(a)); AbilityRuntime.Cast explicitCast=explicit.cast(new AbilityDefinition(1,"projects:q","q",List.of(new AbilityDefinition.Wait(1))),new AbilityCastContext(UUID.randomUUID(),"projects:q",s,SourceKind.PLAYER,c.origin(),t,Map.of())); explicitCast.cancel(AbilityRuntime.CancelReason.EXPLICIT); explicitCast.cancel(AbilityRuntime.CancelReason.EXPLICIT); assert cancelled.size()==2&&cancelled.get(1).hook()==AbilityLifecycleEvent.Hook.CANCEL&&cancelled.get(1).cancelReason()==AbilityRuntime.CancelReason.EXPLICIT;
 }
 static void adapterIsolationAndScalarResolution(){
  AbilityVisualRegistry registry=new AbilityVisualRegistry(); AbilityVisualDefinition.PrimitiveSpec good=new AbilityVisualDefinition.PrimitiveSpec("good",AbilityVisualDefinition.PrimitiveType.CIRCLE,0,1,0xff,1,1,1,new AbilityVisualDefinition.Vec(0,0,0),0,null,AbilityVisualDefinition.ActionField.RADIUS,null,null,null,null,null,null,0,List.of()); AbilityVisualDefinition.PrimitiveSpec bad=new AbilityVisualDefinition.PrimitiveSpec("bad",AbilityVisualDefinition.PrimitiveType.CIRCLE,0,1,0xff,1,1,1,new AbilityVisualDefinition.Vec(0,0,0),0,null,AbilityVisualDefinition.ActionField.INNER_RADIUS,null,null,null,null,null,null,0,List.of()); registry.register(new AbilityVisualDefinition(1,"projects:vfx/test",List.of(new AbilityVisualDefinition.HookBinding(AbilityLifecycleEvent.Hook.TELEGRAPH,List.of(new AbilityVisualDefinition.Emission("bad",0,List.of(bad)),new AbilityVisualDefinition.Emission("good",0,List.of(good))))))); registry.bind(new AbilityVisualBinding("projects:test","projects:vfx/test")); List<AbilityVfxPacket.Cue> sent=new ArrayList<>(); AbilityVisualAdapter adapter=new AbilityVisualAdapter(registry,sent::add); AbilityCastContext c=new AbilityCastContext(UUID.randomUUID(),"projects:test",new AbilityCastContext.EntityRef(UUID.randomUUID()),SourceKind.PLAYER,new AbilityCastContext.Origin(UUID.randomUUID(),"minecraft:overworld",0,0,0),null,Map.of()); AbilityDefinition.CircleTelegraph action=new AbilityDefinition.CircleTelegraph(TargetSelector.SELF,TargetSelector.SELF,3,1,true); adapter.onLifecycle(new AbilityLifecycleEvent(c,AbilityLifecycleEvent.Hook.TELEGRAPH,0,action,null,null,frame(c))); assert sent.size()==1&&sent.getFirst().primitives().getFirst().radius()==3;
  new AbilityVisualAdapter(registry,cue->{throw new IllegalStateException();}).onLifecycle(new AbilityLifecycleEvent(c,AbilityLifecycleEvent.Hook.TELEGRAPH,0,action,null,null,frame(c)));
 }
 static void wireGolden()throws Exception { byte[] got=AbilityVfxPacket.encode(canonical()); Path fixture=Path.of("src/test/resources/protocol/ability-vfx-v1-golden.hex"); byte[] text=Files.readAllBytes(fixture); String expected=new String(text,java.nio.charset.StandardCharsets.UTF_8).replaceAll("\\s",""); byte[] decoded=java.util.HexFormat.of().parseHex(expected); assert hex(got).equalsIgnoreCase(expected); assert sha(decoded).equals("c1e1c796505487ac5bb52d12f982c3ef77c645220d412c743afcefc85c4b1bb3"); assert sha(text).equals("20144abb25012915ad872dbfdaf599ad28ee1698adf993145c1e71e225257091"); assert got[0]==1; AbilityVfxPacket.Cue cue=canonical(); expect(()->new AbilityVfxPacket.Cue(cue.session(),0,cue.cueId(),cue.castId(),cue.visualId(),cue.hook(),cue.actionIndex(),cue.emissionIndex(),cue.serverTickAtSend(),cue.startTick(),cue.cueDurationTicks(),cue.anchor(),cue.primitives())); expect(()->new AbilityVfxPacket.Cue(cue.session(),1,cue.cueId(),cue.castId(),cue.visualId(),cue.hook(),cue.actionIndex(),cue.emissionIndex(),cue.serverTickAtSend(),cue.startTick(),1,cue.anchor(),cue.primitives())); expect(()->new AbilityVfxPacket.Primitive(AbilityVisualDefinition.PrimitiveType.CIRCLE,0,1,0,Double.NaN,1,1,new AbilityVisualDefinition.Vec(0,0,0),0,0,1,0,0,0,0,0,0,0,List.of())); }
 static AbilityVfxPacket.Cue canonical(){ UUID w=UUID.fromString("11111111-2222-3333-4444-555555555555"); AnchorFrame f=new AnchorFrame(w,"minecraft:overworld",1.25,64,-2.5,0,0,2,0,2,0); var p=new AbilityVfxPacket.Primitive(AbilityVisualDefinition.PrimitiveType.CIRCLE,2,20,0x7f8040ff,.25,12,99,new AbilityVisualDefinition.Vec(1,2,3),.5,0,3.0,0,0,0,0,0,0,0,List.of()); return new AbilityVfxPacket.Cue(UUID.fromString("aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"),7,UUID.fromString("01234567-89ab-cdef-0123-456789abcdef"),UUID.fromString("fedcba98-7654-3210-fedc-ba9876543210"),"projects:vfx/golden",AbilityLifecycleEvent.Hook.TELEGRAPH,0,0,100,100,22,f,List.of(p)); }
 static byte[] particleWire(){AbilityVfxPacket.Cue base=canonical();var p=base.primitives().getFirst();var particle=new AbilityVfxPacket.Primitive(p.type(),p.delayTicks(),p.durationTicks(),p.argb(),p.width(),p.density(),p.seed(),p.localOffset(),p.yawRadians(),p.size(),p.radius(),p.length(),p.height(),p.angle(),p.startAngle(),p.sweepAngle(),p.turns(),p.count(),p.controlPoints(),AbilityVisualDefinition.Appearance.particle("minecraft:flame"));return AbilityVfxPacket.encode(new AbilityVfxPacket.Cue(base.session(),base.sequence(),base.cueId(),base.castId(),base.visualId(),base.hook(),base.actionIndex(),base.emissionIndex(),base.serverTickAtSend(),base.startTick(),base.cueDurationTicks(),base.anchor(),List.of(particle)));}
 static void appearanceRuntime(){
  assert AbilityVisualDefinition.Appearance.particleIds().equals(Set.of("minecraft:ash","minecraft:cloud","minecraft:crit","minecraft:enchanted_hit","minecraft:end_rod","minecraft:firework","minecraft:flame","minecraft:soul","minecraft:soul_fire_flame"));
  expect(()->AbilityVisualDefinition.Appearance.particle("minecraft:dust")); expect(()->new AbilityVisualDefinition.Appearance(AbilityVisualDefinition.AppearanceKind.PARTICLE,"bad"));
  AbilityVfxPacket.Cue base=canonical(); var particle=new AbilityVfxPacket.Primitive(base.primitives().getFirst().type(),2,20,0x7f8040ff,.25,12,99,new AbilityVisualDefinition.Vec(1,2,3),.5,0,3,0,0,0,0,0,0,0,List.of(),AbilityVisualDefinition.Appearance.particle("minecraft:flame")); byte[] debug=AbilityVfxPacket.encode(base), v2=AbilityVfxPacket.encode(new AbilityVfxPacket.Cue(base.session(),base.sequence(),base.cueId(),base.castId(),base.visualId(),base.hook(),base.actionIndex(),base.emissionIndex(),base.serverTickAtSend(),base.startTick(),base.cueDurationTicks(),base.anchor(),List.of(particle))); boolean primitiveV2=false;for(int n=0;n<v2.length-1;n++)if(v2[n]==AbilityVisualDefinition.PrimitiveType.CIRCLE.ordinal()&&v2[n+1]==2)primitiveV2=true; assert v2.length>debug.length&&primitiveV2; try{assert hex(v2).equals(Files.readString(Path.of("src/test/resources/protocol/ability-vfx-v2-particle-golden.hex")).trim());}catch(Exception e){throw new AssertionError(e);} // version-2 payload suffix is kind + u16 UTF-8 appearance id
 }
 static AnchorFrame frame(AbilityCastContext c){return new AnchorFrame(c.origin().worldId(),c.origin().dimension(),0,0,0,0,0,1,0,1,0);} static String hex(byte[] b){StringBuilder x=new StringBuilder();for(byte v:b)x.append(String.format("%02x",v));return x.toString();} static String sha(byte[] b)throws Exception{return hex(MessageDigest.getInstance("SHA-256").digest(b));} static void expect(Runnable r){try{r.run();throw new AssertionError();}catch(IllegalArgumentException ok){}} static final class Immediate implements AbilityRuntime.Scheduler{public Scheduled schedule(int t,Runnable r){r.run();return ()->{};}}
}
