package io.github.gyai.projects.network;

import io.github.gyai.projects.ability.*;
import java.io.*; import java.nio.charset.StandardCharsets; import java.util.*;

/** Authoritative byte layout for projects:ability_vfx_v1. Primitive payloads are length-framed for forward skipping. */
public final class AbilityVfxPacket {
    public static final String CHANNEL="projects:ability_vfx_v1"; public static final int VERSION=1, MAX_PACKET_BYTES=16_384;
    public record Cue(UUID session, long sequence, UUID cueId, UUID castId, String visualId, AbilityLifecycleEvent.Hook hook, int actionIndex, int emissionIndex, long serverTickAtSend, long startTick, int cueDurationTicks, AnchorFrame anchor, List<Primitive> primitives) {
        public Cue { Objects.requireNonNull(session);Objects.requireNonNull(cueId);Objects.requireNonNull(castId); Objects.requireNonNull(visualId);Objects.requireNonNull(hook);Objects.requireNonNull(anchor); primitives=List.copyOf(primitives); int required=primitives.stream().mapToInt(p->p.delayTicks()+p.durationTicks()).max().orElse(0), samples=primitives.stream().mapToInt(p->p.type()==AbilityVisualDefinition.PrimitiveType.BURST?p.count():p.density()).sum(); if(sequence<=0||visualId.getBytes(StandardCharsets.UTF_8).length>96||actionIndex< -1||emissionIndex<0||cueDurationTicks<required||cueDurationTicks<1||cueDurationTicks>1200||samples>2048||primitives.isEmpty()||primitives.size()>16) throw new IllegalArgumentException("Invalid vfx cue"); }
    }
    public record Primitive(AbilityVisualDefinition.PrimitiveType type,int delayTicks,int durationTicks,int argb,double width,int density,long seed,AbilityVisualDefinition.Vec localOffset,double yawRadians,double size,double radius,double length,double height,double angle,double startAngle,double sweepAngle,double turns,int count,List<AbilityVisualDefinition.Vec> controlPoints,AbilityVisualDefinition.Appearance appearance,MotionSpec motion) {
        /** Exact v1 source signature; old callers emit a byte-identical DEBUG_QUAD payload. */
        public Primitive(AbilityVisualDefinition.PrimitiveType type,int delayTicks,int durationTicks,int argb,double width,int density,long seed,AbilityVisualDefinition.Vec localOffset,double yawRadians,double size,double radius,double length,double height,double angle,double startAngle,double sweepAngle,double turns,int count,List<AbilityVisualDefinition.Vec> controlPoints) { this(type,delayTicks,durationTicks,argb,width,density,seed,localOffset,yawRadians,size,radius,length,height,angle,startAngle,sweepAngle,turns,count,controlPoints,AbilityVisualDefinition.Appearance.DEBUG_QUAD,MotionSpec.LEGACY_DEFAULT); }
        public Primitive(AbilityVisualDefinition.PrimitiveType type,int delayTicks,int durationTicks,int argb,double width,int density,long seed,AbilityVisualDefinition.Vec localOffset,double yawRadians,double size,double radius,double length,double height,double angle,double startAngle,double sweepAngle,double turns,int count,List<AbilityVisualDefinition.Vec> controlPoints,AbilityVisualDefinition.Appearance appearance) { this(type,delayTicks,durationTicks,argb,width,density,seed,localOffset,yawRadians,size,radius,length,height,angle,startAngle,sweepAngle,turns,count,controlPoints,appearance,MotionSpec.LEGACY_DEFAULT); }
        public Primitive { controlPoints=List.copyOf(controlPoints); if(type==null||appearance==null||motion==null||delayTicks<0||delayTicks>200||durationTicks<1||durationTicks>1200||delayTicks+durationTicks>1200||!finite(width,yawRadians,size,radius,length,height,angle,startAngle,sweepAngle,turns)||Math.abs(size)>128||Math.abs(radius)>128||Math.abs(length)>128||Math.abs(height)>128||Math.abs(angle)>Math.PI||Math.abs(sweepAngle)>4*Math.PI||Math.abs(turns)>32||width<=0||width>16||density<1||density>256||localOffset==null||count<0||count>64||controlPoints.size()>8) throw new IllegalArgumentException("Invalid resolved primitive"); check(type,size,radius,length,height,angle,startAngle,sweepAngle,turns,count,controlPoints); motion.validateFor(type); }
        private static void check(AbilityVisualDefinition.PrimitiveType t,double s,double r,double l,double h,double a,double start,double sweep,double turns,int count,List<?> cp) { boolean z=v(s,r,l,h,a,start,sweep,turns)&&count==0; switch(t) { case POINT -> ok(s>0&&r==0&&l==0&&h==0&&a==0&&start==0&&sweep==0&&turns==0&&count==0&&cp.isEmpty()); case LINE -> ok(l>0&&s==0&&r==0&&h==0&&a==0&&start==0&&sweep==0&&turns==0&&count==0&&(cp.isEmpty()||cp.size()==2)); case ARC -> ok(r>0&&sweep!=0&&s==0&&l==0&&h==0&&a==0&&turns==0&&count==0&&cp.isEmpty()); case CIRCLE -> ok(r>0&&s==0&&l==0&&h==0&&a==0&&sweep==0&&turns==0&&count==0&&cp.isEmpty()); case SPHERE -> ok(r>0&&s==0&&l==0&&h==0&&a==0&&start==0&&sweep==0&&turns==0&&count==0&&cp.isEmpty()); case CONE -> ok(l>0&&a>0&&a<Math.PI&&s==0&&r==0&&h==0&&start==0&&sweep==0&&turns==0&&count==0&&cp.isEmpty()); case SPIRAL -> ok(r>0&&h>=0&&turns>0&&s==0&&l==0&&a==0&&start==0&&sweep==0&&count==0&&cp.isEmpty()); case WAVE -> ok(l>0&&r>0&&h>=0&&s==0&&a==0&&start==0&&sweep==0&&turns==0&&count==0&&cp.isEmpty()); case BEZIER -> ok(z&&(cp.size()==3||cp.size()==4)); case BURST -> ok(r>0&&count>0&&s==0&&l==0&&h==0&&a==0&&start==0&&sweep==0&&turns==0&&cp.isEmpty()); } }
        private static boolean v(double...x){for(double d:x)if(d!=0)return false;return true;} private static void ok(boolean value){if(!value)throw new IllegalArgumentException("Invalid primitive type slots");}
    }
    public static byte[] encode(Cue cue) {
        try { ByteArrayOutputStream raw=new ByteArrayOutputStream(); DataOutputStream out=new DataOutputStream(raw); out.writeByte(VERSION); uuid(out,cue.session());out.writeLong(cue.sequence());uuid(out,cue.cueId());uuid(out,cue.castId());string(out,cue.visualId(),96);out.writeByte(cue.hook().ordinal());out.writeInt(cue.actionIndex());out.writeInt(cue.emissionIndex()); AnchorFrame a=cue.anchor().normalized();uuid(out,a.worldId());string(out,a.dimension(),128); doubles(out,a.x(),a.y(),a.z(),a.forwardX(),a.forwardY(),a.forwardZ(),a.upX(),a.upY(),a.upZ());out.writeLong(cue.serverTickAtSend());out.writeLong(cue.startTick());out.writeInt(cue.cueDurationTicks());out.writeByte(cue.primitives().size()); for(Primitive p:cue.primitives()) primitive(out,p);out.flush();if(raw.size()>MAX_PACKET_BYTES)throw new IllegalArgumentException("Vfx packet too large");return raw.toByteArray(); }catch(IOException e){throw new IllegalStateException(e);}
    }
    /** Returns the old-client-safe cue, dropping all nonlegacy Motion primitives. */
    public static Optional<Cue> legacyOnly(Cue cue) {
        List<Primitive> legacy = cue.primitives().stream().filter(p -> p.motion().isLegacyDefault()).toList();
        if (legacy.isEmpty()) return Optional.empty();
        if (legacy.size() == cue.primitives().size()) return Optional.of(cue);
        return Optional.of(new Cue(cue.session(), cue.sequence(), cue.cueId(), cue.castId(), cue.visualId(), cue.hook(),
                cue.actionIndex(), cue.emissionIndex(), cue.serverTickAtSend(), cue.startTick(), cue.cueDurationTicks(),
                cue.anchor(), legacy));
    }
    private static void primitive(DataOutputStream out,Primitive p)throws IOException { ByteArrayOutputStream payload=new ByteArrayOutputStream();DataOutputStream q=new DataOutputStream(payload);q.writeShort(p.delayTicks());q.writeShort(p.durationTicks());q.writeByte(p.argb()>>>16);q.writeByte(p.argb()>>>8);q.writeByte(p.argb());q.writeByte(p.argb()>>>24);q.writeDouble(p.width());q.writeShort(p.density());q.writeLong(p.seed());doubles(q,p.localOffset().x(),p.localOffset().y(),p.localOffset().z(),p.yawRadians(),p.size(),p.radius(),p.length(),p.height(),p.angle(),p.startAngle(),p.sweepAngle(),p.turns());q.writeShort(p.count());q.writeByte(p.controlPoints().size());for(var v:p.controlPoints())doubles(q,v.x(),v.y(),v.z());if(p.appearance().kind()==AbilityVisualDefinition.AppearanceKind.PARTICLE){q.writeByte(p.appearance().kind().ordinal());string(q,p.appearance().id(),96);}q.flush();if(payload.size()>65535)throw new IllegalArgumentException("Primitive too large");out.writeByte(p.type().ordinal());out.writeByte(p.appearance().kind()==AbilityVisualDefinition.AppearanceKind.DEBUG_QUAD?1:2);out.writeShort(payload.size());out.write(payload.toByteArray()); }
    private static void uuid(DataOutputStream o,UUID v)throws IOException{o.writeLong(v.getMostSignificantBits());o.writeLong(v.getLeastSignificantBits());}
    private static void string(DataOutputStream o,String v,int max)throws IOException{byte[] b=v.getBytes(StandardCharsets.UTF_8);if(b.length>max)throw new IllegalArgumentException("String too long");o.writeShort(b.length);o.write(b);}
    private static void doubles(DataOutputStream o,double... x)throws IOException{for(double v:x)o.writeDouble(v);} private static boolean finite(double...x){for(double v:x)if(!Double.isFinite(v))return false;return true;}
}
