package io.github.gyai.projects.player;

public enum StatType {
    MAX_HEALTH_FLAT,
    MAX_HEALTH_PERCENT,

    PHYSICAL_ATTACK_FLAT,
    PHYSICAL_ATTACK_PERCENT,
    MAGICAL_ATTACK_FLAT,
    MAGICAL_ATTACK_PERCENT,

    ATTACK_SPEED_PERCENT,
    CAST_SPEED_PERCENT,
    COOLDOWN_RECOVERY_PERCENT,

    DAMAGE_INCREASE_PERCENT,
    PHYSICAL_DAMAGE_INCREASE_PERCENT,
    MAGICAL_DAMAGE_INCREASE_PERCENT,
    BASIC_ATTACK_DAMAGE_INCREASE_PERCENT,
    SKILL_DAMAGE_INCREASE_PERCENT,

    CRITICAL_CHANCE_PERCENT,
    CRITICAL_DAMAGE_BONUS,

    PHYSICAL_PENETRATION_FLAT,
    PHYSICAL_PENETRATION_PERCENT,
    MAGICAL_PENETRATION_FLAT,
    MAGICAL_PENETRATION_PERCENT,

    PHYSICAL_DEFENSE_FLAT,
    PHYSICAL_DEFENSE_PERCENT,
    MAGICAL_DEFENSE_FLAT,
    MAGICAL_DEFENSE_PERCENT,
    DAMAGE_REDUCTION_PERCENT,

    HEALING_POWER_FLAT,
    HEALING_POWER_PERCENT,
    OUTGOING_HEALING_PERCENT,
    INCOMING_HEALING_PERCENT,
    LIFESTEAL_PERCENT,
    SHIELD_POWER_PERCENT,

    MOVE_SPEED_FLAT,
    MOVE_SPEED_PERCENT,

    MAX_MANA_FLAT,
    MAX_MANA_PERCENT,
    MANA_REGEN_FLAT,
    MANA_REGEN_PERCENT,

    MAX_RESOURCE_FLAT,
    MAX_RESOURCE_PERCENT,
    RESOURCE_REGEN_FLAT,
    RESOURCE_REGEN_PERCENT
}
